### ISSUE TITLE
broken evil-org-open-links ?

### ISSUE THREAD

**Issue by muahah** [edwtjo/evil-org-mode#25]
Hi,
I downloaded evil-org-mode from Melpa repository,
I'm pretty happy with it, so before anything else, thank you.

I still have some difficulties to use the "evil-org-open-links" function bound to \<leader\>l.
It work fine on external links (such as URL or files) but not with simple headings references ("[[Heading_name]]" that should lead me to the coresponding heading, for example), where emacs freeze (messages buffer displaying "Position saved to mark ring, go back with C-c &. [3028 times]")

I use "org-open-at-point" instead for now, but i'm sure there is a more elegant way to solve this problem.

**Comment by wsdookadr** [comment]
@muahah I'll first outline what the main goal of `evil-org-open-links` is. This function was developed so that a user could make a visual selection containing links to URIs that a browser understands(mainly  http/https/ftp) and open all of those links in the visual selection in the browser.
I'm interested in knowing what your use-case is for links like `"[[heading_name]]"`.
I am currently thinking that one way of solving this would be skipping those links or opening them in a different way, but in order to expand further on that I need to know how they are opened.

**Comment by muahah** [comment]
@wsdookadr Thanks for the clarifications, 
It appears that i misunderstood the use of `evil-org-open-links`.

I wanted to set a single keybinding to follow link at point in normal state and to follow a set of links in visual mode.

I tried to define a new function `org-open-link-or-links` in my init.el file to do so :
```elisp
(defun org-open-link-or-links ()
  (if (memq evil-state '(normal))
      (org-open-at-point)
    (if (memq evil-state '(visual))
	'evil-org-open-links)))
```
But i have troubles handling `evil-org-open-links` which is defined as an operator
(does'nt know if you're interested by such function, by the way...).
